### ISSUE TITLE
How to create a release apk that can be installed on device

### ISSUE THREAD

**Issue by bobthekingofegypt** [VMadalin/kotlin-sample-app#10]
## Description

I'm trying to use this project as a sort of bootstrap for a new android project,  when a signed release apk is created by android studio and installed it crashes instantly due to being unable to find the dynamic module fragments.

## Basic Information

-   OS version: Linux
-   App version: android studio 3.5.3

## Details

Using android studios Build -> generate signed apk -> normal apk
If you install that generated apk it will crash with a classpath issue with Coil, if you fix that (I added it to core's dependencies) then you get

```
Process: com.vmadalin.android, PID: 18602
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vmadalin.android/com.vmadalin.android.SampleMainActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class fragment
     Caused by: androidx.fragment.app.Fragment$e: Unable to instantiate fragment com.vmadalin.dynamicfeatures.home.ui.HomeFragment: make sure class name exists
```

I assumed as all dynamic modules are set to install time delivery a monolith apk should work.  I also tried creating an aab, using bundletool to create a universal apk and installing that but I ended up with the same error.

What is the correct way to do a release APK?

**Comment by tidoemanuele** [comment]
@bobthekingofegypt I had the same problem. 
Please read [this post](http://pgreze.netlify.com/post/2019-10-02-universal-apk-commands/#traditional-vs-universal-apk) and [this thread](https://github.com/DroidKaigi/conference-app-2020/issues/217). I tried differents ways until I found this gradle task: **packageProdReleaseUniversalApk** 

But you need to do the follow before:
- add COIL to app dependencies  list
- set instant false in all features and change dist:fusing from false to true
- add this proguard rules to app module ` -keep class com.vmadalin.** { *; }`

also this approach works:
1) run this gradle task: packageProdReleaseBundle 
2) download this[bundletool.jar.zip](url) unzip it and just to prove that works put everythings in a folder (bundletool.jar, your aab file and store key)
3) edit properly and run this command: java -jar bundletool-all.jar build-apks --bundle=app-prod-release.aab --output=app-prod-release.apks --mode=universal --ks=mykeyfile.jks --ks-pass=pass:mypass --ks-key-alias='my alias' --key-pass=pass:mypass
4) rename app-prod-release.apks to app-prod-release.zip
5) unzip app-prod-release.zip
6) run your app-prod-release.apk in your android device

Check my [PR](https://github.com/VMadalin/kotlin-sample-app/pull/11)

**Comment by mohammadestk** [comment]
when minify is enabled, production release app will crash. any idea about how to fix this problem?
I think this issue for obfuscation of fragments and navigation architecture components.
even I used new navigation system for dynamic feature module. it works fine in debug. but in release I faced this error:

Caused by: android.view.InflateException: Binary XML file line 9 in layout/activity_main: Binary XML file line 9 in layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line 9 in layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: androidx.fragment.app.Fragment$d: Unable to instantiate fragment androidx.navigation.dynamicfeatures.fragment.DynamicNavHostFragment: make sure class name exists

**Comment by VMadalin** [comment]
Sorry for the delay regarding this issue, but I haven't the time to dedicate to this project. First of all, thank you @bobthekingofegypt for your bug reporting and also @tidoemanuele for the research. Following the google recommendations about how to test dynamic delivery:
> Important:
> 
> The easiest way to test applications using dynamic delivery is to use internal app sharing. This allows you to distribute a link directly to the beta tester of your apk or app bundle, independently on the version number. This works even for debug build!
> You can find more information in the [documentation](https://support.google.com/googleplay/android-developer/answer/9303479?hl=en)

Basically you cannot test them generating an old format `.apk`, for this reason, you should generate a `.aab` and upload it to google play console. I tested this but it still don't work because the following conflict between `Dynamic Features`, `Data Binding` and `MinifyEnabled` (https://github.com/android/plaid/issues/764), but you can easily fix the below line on the `proguard-rules.pro`:
```
-keep class **.DataBinderMapperImpl { *; }
```

I hope i can help you with, if not please reopen the ticket. Thank you
